# Support platforms
buy_me_a_coffee: laystorages
kofi: danilofrazao-dev
custom: ["https://buy.stripe.com/fZucMYe1U7Vt0jDaVWfQI03", "https://buymeacoffee.com/laystorages", "https://ko-fi.com/danilofrazao-dev"]
