# Support platforms
buy_me_a_coffee: laystorages
kofi: danilofrazao-dev
custom: ["https://buy.stripe.com/5kQ00c3ngcbJeat9RSfQI02", "https://buymeacoffee.com/laystorages", "https://ko-fi.com/danilofrazao-dev"]
